var arrays = {
	cuisines: [
		'American',
		'Kid-Friendly',
		'Italian',
		'Asian',
		'Mexican',
		'Southern & Soul Food',
		'French',
		'Southwestern',
		'Barbecue',
		'Indian',
		'Chinese',
		'Cajun & Creole',
		'Mediterranean',
		'Greek',
		'English',
		'Spanish',
		'German',
		'Thai',
		'Moroccan',
		'Irish',
		'Japanese',
		'Cuban',
		'Hawaiian',
		'Swedish',
		'Portugese',
		'Hungarian'
	],
	cuisinesSearch: [
		"cuisine^cuisine-american",
		"cuisine^cuisine-kid-friendly",
		"cuisine^cuisine-italian",
		"cuisine^cuisine-asian",
		"cuisine^cuisine-mexican",
		"cuisine^cuisine-southern",
		"cuisine^cuisine-french",
		"cuisine^cuisine-southwestern",
		"cuisine^cuisine-barbecue-bbq",
		"cuisine^cuisine-indian",
		"cuisine^cuisine-chinese",
		"cuisine^cuisine-cajun",
		"cuisine^cuisine-mediterranean",
		"cuisine^cuisine-greek",
		"cuisine^cuisine-english",
		"cuisine^cuisine-spanish",
		"cuisine^cuisine-german",
		"cuisine^cuisine-thai",
		"cuisine^cuisine-moroccan",
		"cuisine^cuisine-irish",
		"cuisine^cuisine-japanese",
		"cuisine^cuisine-cuban",
		"cuisine^cuisine-hawaiian",
		"cuisine^cuisine-swedish",
		"cuisine^cuisine-portuguese",
		"cuisine^cuisine-hungarian"
	],
	dietsSearch: [
		'388^Lacto%20vegetarian',
		'389^Ovo%20vegetarian',
		'390^Pescetarian',
		'386^Vegan',
		'387^Lacto-ovo%20vegetarian',
		'403^Paleo'
	],
	diets: [
		'Lacto vegetarian',
		'Ovo vegetarian',
		'Pescetarian',
		'Vegan',
		'Lacto-ovo vegetarian',
		'Paleo'
	],
	allergiesSearch: [
		'393^Gluten-Free',
		'394^Peanut-Free',
		'398^Seafood-Free',
		'399^Sesame-Free',
		'400^Soy-Free',
		'396^Dairy-Free',
		'397^Egg-Free',
		'401^Sulfite-Free',
		'395^Tree Nut-Free',
		'392^Wheat-Free'
	],
	allergies: [
		'Gluten-Free',
		'Peanut-Free',
		'Seafood-Free',
		'Sesame-Free',
		'Soy-Free',
		'Dairy-Free',
		'Egg-Free',
		'Sulfite-Free',
		'Tree Nut-Free',
		'Wheat-Free'
	],
	searchJSON: [{"R":{"res_id":16907121},"apikey":"c3f72d6b6e5474936f491150b9e3c476","id":"16907121","name":"Meehan's Public House","url":"https://www.zomato.com/atlanta/meehans-public-house-downtown?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1","location":{"address":"200 Peachtree Street 30303","locality":"Downtown","city":"Atlanta","city_id":288,"latitude":"33.7590292000","longitude":"-84.3878560000","zipcode":"30303","country_id":216,"locality_verbose":"Downtown, Atlanta"},"switch_to_order_menu":0,"cuisines":"American, Irish, Bar Food","average_cost_for_two":25,"price_range":2,"currency":"$","offers":[],"thumb":"","user_rating":{"aggregate_rating":"3.9","rating_text":"Good","rating_color":"9ACD32","votes":"218"},"photos_url":"https://www.zomato.com/atlanta/meehans-public-house-downtown/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop","menu_url":"https://www.zomato.com/atlanta/meehans-public-house-downtown/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop","featured_image":"","has_online_delivery":0,"is_delivering_now":0,"deeplink":"zomato://restaurant/16907121","has_table_booking":0,"events_url":"https://www.zomato.com/atlanta/meehans-public-house-downtown/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1"},{"R":{"res_id":16895962},"apikey":"c3f72d6b6e5474936f491150b9e3c476","id":"16895962","name":"Sun Dial Restaurant, Bar & View","url":"https://www.zomato.com/atlanta/sun-dial-restaurant-bar-view-downtown?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1","location":{"address":"The Westin Peachtree Plaza, 210 Peachtree Street NE, Downtown, Atlanta 30303","locality":"Downtown","city":"Atlanta","city_id":288,"latitude":"33.7591658000","longitude":"-84.3880638000","zipcode":"30303","country_id":216,"locality_verbose":"Downtown, Atlanta"},"switch_to_order_menu":0,"cuisines":"American, New American","average_cost_for_two":120,"price_range":4,"currency":"$","offers":[],"thumb":"https://b.zmtcdn.com/data/pictures/2/16895962/64e51a0eff0540cb13bc4cd79c61f5f3_featured_v2.jpg","user_rating":{"aggregate_rating":"3.7","rating_text":"Good","rating_color":"9ACD32","votes":"291"},"photos_url":"https://www.zomato.com/atlanta/sun-dial-restaurant-bar-view-downtown/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop","menu_url":"https://www.zomato.com/atlanta/sun-dial-restaurant-bar-view-downtown/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop","featured_image":"https://b.zmtcdn.com/data/pictures/2/16895962/64e51a0eff0540cb13bc4cd79c61f5f3_featured_v2.jpg","has_online_delivery":0,"is_delivering_now":0,"deeplink":"zomato://restaurant/16895962","has_table_booking":0,"events_url":"https://www.zomato.com/atlanta/sun-dial-restaurant-bar-view-downtown/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1"},{"R":{"res_id":16894570},"apikey":"c3f72d6b6e5474936f491150b9e3c476","id":"16894570","name":"Ray's in the City","url":"https://www.zomato.com/atlanta/rays-in-the-city-downtown?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1","location":{"address":"240 Peachtree Street NW, Downtown, Atlanta 30303","locality":"Downtown","city":"Atlanta","city_id":288,"latitude":"33.7608941000","longitude":"-84.3877537000","zipcode":"30303","country_id":216,"locality_verbose":"Downtown, Atlanta"},"switch_to_order_menu":0,"cuisines":"Seafood, Steak, Sushi","average_cost_for_two":75,"price_range":4,"currency":"$","offers":[],"thumb":"https://b.zmtcdn.com/data/pictures/0/16894570/79186b889ee675b6311b7f891e2d30fc_featured_v2.jpg","user_rating":{"aggregate_rating":"3.8","rating_text":"Good","rating_color":"9ACD32","votes":"346"},"photos_url":"https://www.zomato.com/atlanta/rays-in-the-city-downtown/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop","menu_url":"https://www.zomato.com/atlanta/rays-in-the-city-downtown/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop","featured_image":"https://b.zmtcdn.com/data/pictures/0/16894570/79186b889ee675b6311b7f891e2d30fc_featured_v2.jpg","has_online_delivery":0,"is_delivering_now":0,"deeplink":"zomato://restaurant/16894570","has_table_booking":0,"events_url":"https://www.zomato.com/atlanta/rays-in-the-city-downtown/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1"},{"R":{"res_id":16907805},"apikey":"c3f72d6b6e5474936f491150b9e3c476","id":"16907805","name":"Sweet Georgia's Juke Joint","url":"https://www.zomato.com/atlanta/sweet-georgias-juke-joint-downtown?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1","location":{"address":"200 Peachtree Street, Downtown, Atlanta 30303","locality":"Downtown","city":"Atlanta","city_id":288,"latitude":"33.7590292000","longitude":"-84.3878560000","zipcode":"30303","country_id":216,"locality_verbose":"Downtown, Atlanta"},"switch_to_order_menu":0,"cuisines":"Southern","average_cost_for_two":25,"price_range":2,"currency":"$","offers":[],"thumb":"https://b.zmtcdn.com/data/pictures/5/16907805/c555003a54c835e9430b0d6f17764f26_featured_v2.jpg","user_rating":{"aggregate_rating":"3.9","rating_text":"Good","rating_color":"9ACD32","votes":"346"},"photos_url":"https://www.zomato.com/atlanta/sweet-georgias-juke-joint-downtown/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop","menu_url":"https://www.zomato.com/atlanta/sweet-georgias-juke-joint-downtown/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop","featured_image":"https://b.zmtcdn.com/data/pictures/5/16907805/c555003a54c835e9430b0d6f17764f26_featured_v2.jpg","has_online_delivery":0,"is_delivering_now":0,"deeplink":"zomato://restaurant/16907805","has_table_booking":0,"events_url":"https://www.zomato.com/atlanta/sweet-georgias-juke-joint-downtown/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1"},{"R":{"res_id":16906365},"apikey":"c3f72d6b6e5474936f491150b9e3c476","id":"16906365","name":"No Mas Cantina","url":"https://www.zomato.com/atlanta/no-mas-cantina-downtown?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1","location":{"address":"180 Walker Street SW, Downtown, Atlanta 30313","locality":"Downtown","city":"Atlanta","city_id":288,"latitude":"33.7498012000","longitude":"-84.4009361000","zipcode":"30313","country_id":216,"locality_verbose":"Downtown, Atlanta"},"switch_to_order_menu":0,"cuisines":"Mexican","average_cost_for_two":25,"price_range":2,"currency":"$","offers":[],"thumb":"https://b.zmtcdn.com/data/pictures/5/16906365/b9a40ab361b80535d3e9477b4e7040d3_featured_v2.jpg","user_rating":{"aggregate_rating":"3.8","rating_text":"Good","rating_color":"9ACD32","votes":"455"},"photos_url":"https://www.zomato.com/atlanta/no-mas-cantina-downtown/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop","menu_url":"https://www.zomato.com/atlanta/no-mas-cantina-downtown/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop","featured_image":"https://b.zmtcdn.com/data/pictures/5/16906365/b9a40ab361b80535d3e9477b4e7040d3_featured_v2.jpg","has_online_delivery":0,"is_delivering_now":0,"deeplink":"zomato://restaurant/16906365","has_table_booking":0,"events_url":"https://www.zomato.com/atlanta/no-mas-cantina-downtown/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1"},{"R":{"res_id":16896116},"apikey":"c3f72d6b6e5474936f491150b9e3c476","id":"16896116","name":"Ted's Montana Grill","url":"https://www.zomato.com/atlanta/teds-montana-grill-centennial-park-district?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1","location":{"address":"133 Luckie Street NW, Atlanta 30303","locality":"Centennial Park District","city":"Atlanta","city_id":288,"latitude":"33.7586398000","longitude":"-84.3905475000","zipcode":"30303","country_id":216,"locality_verbose":"Centennial Park District, Atlanta"},"switch_to_order_menu":0,"cuisines":"American, Burger, Steak","average_cost_for_two":40,"price_range":3,"currency":"$","offers":[],"thumb":"https://b.zmtcdn.com/data/pictures/6/16896116/6a7094c85c5d6bf9332ed548e2fd72dd_featured_v2.jpg","user_rating":{"aggregate_rating":"4.1","rating_text":"Very Good","rating_color":"5BA829","votes":"419"},"photos_url":"https://www.zomato.com/atlanta/teds-montana-grill-centennial-park-district/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop","menu_url":"https://www.zomato.com/atlanta/teds-montana-grill-centennial-park-district/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop","featured_image":"https://b.zmtcdn.com/data/pictures/6/16896116/6a7094c85c5d6bf9332ed548e2fd72dd_featured_v2.jpg","has_online_delivery":0,"is_delivering_now":0,"deeplink":"zomato://restaurant/16896116","has_table_booking":0,"events_url":"https://www.zomato.com/atlanta/teds-montana-grill-centennial-park-district/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1"},{"R":{"res_id":16902677},"apikey":"c3f72d6b6e5474936f491150b9e3c476","id":"16902677","name":"Legal Sea Foods - Hilton Garden Inn","url":"https://www.zomato.com/atlanta/legal-sea-foods-hilton-garden-inn-centennial-park-district?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1","location":{"address":"Hilton Garden Inn, 275 Baker Street NW 30313","locality":"Centennial Park District","city":"Atlanta","city_id":288,"latitude":"33.7619127000","longitude":"-84.3955689000","zipcode":"30313","country_id":216,"locality_verbose":"Centennial Park District, Atlanta"},"switch_to_order_menu":0,"cuisines":"American, Seafood","average_cost_for_two":40,"price_range":3,"currency":"$","offers":[],"thumb":"https://b.zmtcdn.com/data/pictures/7/16902677/9a18b678af38c82edc7b17e2ff8575eb_featured_v2.jpg","user_rating":{"aggregate_rating":"3.7","rating_text":"Good","rating_color":"9ACD32","votes":"337"},"photos_url":"https://www.zomato.com/atlanta/legal-sea-foods-hilton-garden-inn-centennial-park-district/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop","menu_url":"https://www.zomato.com/atlanta/legal-sea-foods-hilton-garden-inn-centennial-park-district/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop","featured_image":"https://b.zmtcdn.com/data/pictures/7/16902677/9a18b678af38c82edc7b17e2ff8575eb_featured_v2.jpg","has_online_delivery":0,"is_delivering_now":0,"deeplink":"zomato://restaurant/16902677","has_table_booking":0,"events_url":"https://www.zomato.com/atlanta/legal-sea-foods-hilton-garden-inn-centennial-park-district/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1"},{"R":{"res_id":16895687},"apikey":"c3f72d6b6e5474936f491150b9e3c476","id":"16895687","name":"Max Lager's Wood-Fired Grill & Brewery","url":"https://www.zomato.com/atlanta/max-lagers-wood-fired-grill-brewery-downtown?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1","location":{"address":"320 Peachtree Street NE, Downtown, Atlanta 30308","locality":"Downtown","city":"Atlanta","city_id":288,"latitude":"33.7633370000","longitude":"-84.3870350000","zipcode":"30308","country_id":216,"locality_verbose":"Downtown, Atlanta"},"switch_to_order_menu":0,"cuisines":"Pizza, Steak, Burger, New American","average_cost_for_two":40,"price_range":3,"currency":"$","offers":[],"thumb":"https://b.zmtcdn.com/data/pictures/7/16895687/e977b16e97bc44b3bb3504403b832345_featured_v2.jpg","user_rating":{"aggregate_rating":"3.8","rating_text":"Good","rating_color":"9ACD32","votes":"391"},"photos_url":"https://www.zomato.com/atlanta/max-lagers-wood-fired-grill-brewery-downtown/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop","menu_url":"https://www.zomato.com/atlanta/max-lagers-wood-fired-grill-brewery-downtown/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop","featured_image":"https://b.zmtcdn.com/data/pictures/7/16895687/e977b16e97bc44b3bb3504403b832345_featured_v2.jpg","has_online_delivery":0,"is_delivering_now":0,"deeplink":"zomato://restaurant/16895687","has_table_booking":0,"events_url":"https://www.zomato.com/atlanta/max-lagers-wood-fired-grill-brewery-downtown/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1"},{"R":{"res_id":16908380},"apikey":"c3f72d6b6e5474936f491150b9e3c476","id":"16908380","name":"Alma Cocina","url":"https://www.zomato.com/atlanta/alma-cocina-downtown?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1","location":{"address":"191 Peachtree Street NE, Downtown, Atlanta 30303","locality":"Downtown","city":"Atlanta","city_id":288,"latitude":"33.7590381000","longitude":"-84.3872591000","zipcode":"30303","country_id":216,"locality_verbose":"Downtown, Atlanta"},"switch_to_order_menu":0,"cuisines":"Mexican, Spanish, Latin American, Tapas","average_cost_for_two":40,"price_range":3,"currency":"$","offers":[],"thumb":"https://b.zmtcdn.com/data/pictures/0/16908380/625c49a638ce7288efd371ef21edd03c_featured_v2.jpg","user_rating":{"aggregate_rating":"3.9","rating_text":"Good","rating_color":"9ACD32","votes":"274"},"photos_url":"https://www.zomato.com/atlanta/alma-cocina-downtown/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop","menu_url":"https://www.zomato.com/atlanta/alma-cocina-downtown/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop","featured_image":"https://b.zmtcdn.com/data/pictures/0/16908380/625c49a638ce7288efd371ef21edd03c_featured_v2.jpg","has_online_delivery":0,"is_delivering_now":0,"deeplink":"zomato://restaurant/16908380","has_table_booking":0,"events_url":"https://www.zomato.com/atlanta/alma-cocina-downtown/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1"}]
};

module.exports = arrays;