var arrays = {
	cuisines: [
		'American',
		'Kid-Friendly',
		'Italian',
		'Asian',
		'Mexican',
		'Southern & Soul Food',
		'French',
		'Southwestern',
		'Barbecue',
		'Indian',
		'Chinese',
		'Cajun & Creole',
		'Mediterranean',
		'Greek',
		'English',
		'Spanish',
		'German',
		'Thai',
		'Moroccan',
		'Irish',
		'Japanese',
		'Cuban',
		'Hawaiian',
		'Swedish',
		'Portugese',
		'Hungarian'
	],
	cuisinesSearch: [
		"cuisine^cuisine-american",
		"cuisine^cuisine-kid-friendly",
		"cuisine^cuisine-italian",
		"cuisine^cuisine-asian",
		"cuisine^cuisine-mexican",
		"cuisine^cuisine-southern",
		"cuisine^cuisine-french",
		"cuisine^cuisine-southwestern",
		"cuisine^cuisine-barbecue-bbq",
		"cuisine^cuisine-indian",
		"cuisine^cuisine-chinese",
		"cuisine^cuisine-cajun",
		"cuisine^cuisine-mediterranean",
		"cuisine^cuisine-greek",
		"cuisine^cuisine-english",
		"cuisine^cuisine-spanish",
		"cuisine^cuisine-german",
		"cuisine^cuisine-thai",
		"cuisine^cuisine-moroccan",
		"cuisine^cuisine-irish",
		"cuisine^cuisine-japanese",
		"cuisine^cuisine-cuban",
		"cuisine^cuisine-hawaiian",
		"cuisine^cuisine-swedish",
		"cuisine^cuisine-portuguese",
		"cuisine^cuisine-hungarian"
	],
	dietsSearch: [
		'388^Lacto%20vegetarian',
		'389^Ovo%20vegetarian',
		'390^Pescetarian',
		'386^Vegan',
		'387^Lacto-ovo%20vegetarian',
		'403^Paleo'
	],
	diets: [
		'Lacto vegetarian',
		'Ovo vegetarian',
		'Pescetarian',
		'Vegan',
		'Lacto-ovo vegetarian',
		'Paleo'
	],
	allergiesSearch: [
		'393^Gluten-Free',
		'394^Peanut-Free',
		'398^Seafood-Free',
		'399^Sesame-Free',
		'400^Soy-Free',
		'396^Dairy-Free',
		'397^Egg-Free',
		'401^Sulfite-Free',
		'395^Tree Nut-Free',
		'392^Wheat-Free'
	],
	allergies: [
		'Gluten-Free',
		'Peanut-Free',
		'Seafood-Free',
		'Sesame-Free',
		'Soy-Free',
		'Dairy-Free',
		'Egg-Free',
		'Sulfite-Free',
		'Tree Nut-Free',
		'Wheat-Free'
	]
};

module.exports = arrays;